server:
  port: 8088
  
spring:
  cloud:
    gateway:
      routes:
      - uri: http://localhost:8082/
        predicates: 
        - Path=/employees/**
      - uri: http://localhost:8082/
        predicated:
        - Path=/template/emp/**
      
