server:
  port: 8090
spring:
  cloud:
    gateway:
      routes:
      - uri: http://localhost:8083/
        predicates: 
        - Path=/employees/**
      - uri: http://localhost:8084/
        predicated:
        - Path=/template/emp/**
      
