server:
  port: 8088
  
spring:
  cloud:
    gateway:
      routes:
      - uri: http://localhost:8082/
        predicates: 
        - path=/employees/**
      - uri: http://localhost:8080/
        predicated:
        - path=/template/emp/**
      
